/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.josueaguila.pnb.gui;

import javax.swing.JFrame;

/**
 *
 * @author THINKBOOK
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("Pixel & Bean – Sistema de Gestión");
        setSize(900, 600);
        setLocationRelativeTo(null);  // Centra la ventana
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSession = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnDoc = new javax.swing.JMenu();
        mniSession = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnGest = new javax.swing.JMenu();
        mniUser = new javax.swing.JMenuItem();
        mniProduct = new javax.swing.JMenuItem();
        mnOp = new javax.swing.JMenu();
        mniShop = new javax.swing.JMenuItem();
        mnReport = new javax.swing.JMenu();
        mniVentasdia = new javax.swing.JMenuItem();
        mniTop = new javax.swing.JMenuItem();
        mnEvent = new javax.swing.JMenu();
        mniTorneo = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSession.setText("Usuario: (sin iniciar sesión)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblSession)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(lblSession)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        mnDoc.setText("Archivo");

        mniSession.setText("Cerrar sesión");
        mnDoc.add(mniSession);

        mniExit.setText("Salir");
        mnDoc.add(mniExit);

        jMenuBar1.add(mnDoc);

        mnGest.setText("Gestión");

        mniUser.setText("Usuarios");
        mnGest.add(mniUser);

        mniProduct.setText("Productos");
        mnGest.add(mniProduct);

        jMenuBar1.add(mnGest);

        mnOp.setText("Operación");

        mniShop.setText("Ventas");
        mnOp.add(mniShop);

        jMenuBar1.add(mnOp);

        mnReport.setText("Reportes");

        mniVentasdia.setText("Ventas del día");
        mnReport.add(mniVentasdia);

        mniTop.setText("Top productos");
        mnReport.add(mniTop);

        jMenuBar1.add(mnReport);

        mnEvent.setText("Eventos");

        mniTorneo.setText("Torneos");
        mnEvent.add(mniTorneo);

        jMenuBar1.add(mnEvent);

        mnHelp.setText("Ayuda");

        jMenuItem1.setText("Acerca de…");
        mnHelp.add(jMenuItem1);

        jMenuBar1.add(mnHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSession;
    private javax.swing.JMenu mnDoc;
    private javax.swing.JMenu mnEvent;
    private javax.swing.JMenu mnGest;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenu mnOp;
    private javax.swing.JMenu mnReport;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniProduct;
    private javax.swing.JMenuItem mniSession;
    private javax.swing.JMenuItem mniShop;
    private javax.swing.JMenuItem mniTop;
    private javax.swing.JMenuItem mniTorneo;
    private javax.swing.JMenuItem mniUser;
    private javax.swing.JMenuItem mniVentasdia;
    // End of variables declaration//GEN-END:variables
}
