package cl.josueaguila.pnb.gui;

import javax.swing.JOptionPane;
import cl.josueaguila.pnb.service.ProductoService;
import cl.josueaguila.pnb.service.impl.ProductoServiceStub;
import cl.josueaguila.pnb.model.Producto;

public class ProductosPanel extends javax.swing.JPanel {
    private java.util.List<Producto> productos = new java.util.ArrayList<>();
    private ProductoTableModel modelo;
    private ProductoService productoService;
    private Producto productoSeleccionado; 
    private ProductoController controller;
    


    /**
     * Creates new form ProductosPanel
     */
    public ProductosPanel() {
        
        this.controller = ApplicationContext.getInstance().getProductoController();
        
        initComponents();
        modelo = new ProductoTableModel(productos);
        tablaProductos.setModel(modelo);
        cargarProductos();
        limpiarFormulario();
    }


    private void cargarProductos() {
        List<Producto> productos = controller.listarTodos();
        tableModel.setProductos(productos);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBusqueda = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        cmbFiltroCategoria = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        scrollProductos = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        chkActivo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCambiarEstado = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lblBuscar.setText("Buscar: ");
        panelBusqueda.add(lblBuscar);

        txtBuscar.setColumns(15);
        panelBusqueda.add(txtBuscar);

        btnBuscar.setText("🔍");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnBuscar);

        cmbFiltroCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Bebidas", "Snacks", "Tiempo" }));
        panelBusqueda.add(cmbFiltroCategoria);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnNuevo);

        add(panelBusqueda, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(350);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        scrollProductos.setViewportView(tablaProductos);

        jSplitPane1.setLeftComponent(scrollProductos);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(txtNombre, gridBagConstraints);

        jLabel2.setText("Categoría:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jLabel2, gridBagConstraints);

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebidas", "Snacks", "Tiempo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(cmbCategoria, gridBagConstraints);

        jLabel3.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel3, gridBagConstraints);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel1.add(cmbTipo, gridBagConstraints);

        jLabel4.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel1.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtPrecio, gridBagConstraints);

        chkActivo.setText("Activo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(chkActivo, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(btnGuardar, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(btnCancelar, gridBagConstraints);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(btnEliminar, gridBagConstraints);

        btnCambiarEstado.setText("Cambiar Estado");
        btnCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(btnCambiarEstado, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanel1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
        cargarProductoSeleccionado();
    }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            String nombre = txtNombre.getText();
            String categoria = (String) cmbCategoria.getSelectedItem();
            String tipo = (String) cmbTipo.getSelectedItem();
            double precio = Double.parseDouble(txtPrecio.getText());
            if (productoSeleccionado == null) {
                controller.crear(nombre, categoria, tipo, precio);
            } else {
                controller.actualizar(productoSeleccionado.getId(), nombre,
                                    categoria, tipo, precio, chkActivo.isSelected());
            }
            JOptionPane.showMessageDialog(this, "Producto guardado");
            limpiarFormulario();
            cargarProductos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       if (productoSeleccionado == null) return;

        int r = JOptionPane.showConfirmDialog(this,
                "¿Eliminar producto '" + productoSeleccionado.getNombre() + "'?",
                "Confirmar", JOptionPane.YES_NO_OPTION);

        if (r == JOptionPane.YES_OPTION) {
            productoService.eliminar(productoSeleccionado.getId());
            JOptionPane.showMessageDialog(this, "Producto eliminado");
            limpiarFormulario();
            cargarProductos();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
        tablaProductos.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoActionPerformed
        // TODO add your handling code here:
        int fila = tablaProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Producto p = productos.get(fila);
        p.setActivo(!p.isActivo());
        modelo.fireTableDataChanged();
    }//GEN-LAST:event_btnCambiarEstadoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String texto = txtBuscar.getText().trim().toLowerCase();
        if (texto.isEmpty()) {
            modelo.setProductos(productos); // si implementas setProductos en el modelo
            modelo.fireTableDataChanged();
            return;
        }
        java.util.List<Producto> filtrados = new java.util.ArrayList<>();
        for (Producto p : productos) {
            if (p.getNombre().toLowerCase().contains(texto) ||
                p.getCategoria().toLowerCase().contains(texto) ||
                p.getTipo().toLowerCase().contains(texto)) {
                filtrados.add(p);
            }
        }
        modelo.setProductos(filtrados);
        modelo.fireTableDataChanged();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void cargarProductoSeleccionado() {
    int fila = tablaProductos.getSelectedRow();
    if (fila == -1) return;
    Producto p = productos.get(fila);
    txtNombre.setText(p.getNombre());
    cmbCategoria.setSelectedItem(p.getCategoria());
    cmbTipo.setSelectedItem(p.getTipo());
    txtPrecio.setText(String.valueOf((long)p.getPrecio()));
    chkActivo.setSelected(p.isActivo());
}
    
    private void limpiarFormulario() {
    txtNombre.setText("");
    txtPrecio.setText("");
    cmbCategoria.setSelectedIndex(0);
    if (cmbTipo.getItemCount()>0) cmbTipo.setSelectedIndex(0);
    chkActivo.setSelected(true);
    tablaProductos.clearSelection();
}
    
    private boolean validarFormulario() {
    String nombre = txtNombre.getText().trim();
    String categoria = (String) cmbCategoria.getSelectedItem();
    String tipo = (String) cmbTipo.getSelectedItem();
    String precioStr = txtPrecio.getText().trim();

    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío");
        return false;
    }

    if (categoria == null || categoria.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una categoría");
        return false;
    }

    if (tipo == null || tipo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo");
        return false;
    }

    if (precioStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El precio no puede estar vacío");
        return false;
    }

    try {
        double precio = Double.parseDouble(precioStr);
        if (precio <= 0) {
            JOptionPane.showMessageDialog(this, "El precio debe ser mayor a 0");
            return false;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El precio debe ser un número válido");
        return false;
    }

    return true;
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbFiltroCategoria;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JScrollPane scrollProductos;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private class ProductoTableModel extends javax.swing.table.AbstractTableModel {

    private String[] columnNames = { "ID", "Nombre", "Categoría", "Tipo", "Precio", "Activo" };
    private java.util.List<Producto> datos;

    public ProductoTableModel(java.util.List<Producto> datos) {
        this.datos = datos;
    }

    public void setProductos(java.util.List<Producto> datos) {
        this.datos = datos;
        fireTableDataChanged();
    }

    @Override
    public int getRowCount() {
        return datos.size();
    }

    @Override
    public int getColumnCount() {
        return columnNames.length;
    }

    @Override
    public String getColumnName(int column) {
        return columnNames[column];
    }

    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
        Producto p = datos.get(rowIndex);
        switch (columnIndex) {
            case 0: return p.getId();
            case 1: return p.getNombre();
            case 2: return p.getCategoria();
            case 3: return p.getTipo();
            case 4: return String.format("$%,.0f", p.getPrecio());
            case 5: return p.isActivo() ? "Sí" : "No";
            default: return null;
        }
    }

    @Override
    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return false;
    }
}
}
