package cl.josueaguila.pnb.gui;

import cl.josueaguila.pnb.model.Venta;
import cl.josueaguila.pnb.service.VentaService;
import cl.josueaguila.pnb.service.impl.VentaServiceStub;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;



public class ReportesPanel extends javax.swing.JPanel {
    
    private VentaService ventaService;
    private ReporteTableModel tableModel;
   
    
    public ReportesPanel() {
        ventaService = new VentaServiceStub();
        initComponents();
        setupComponents();
    }
    
    private void setupComponents() {

        tableModel = new ReporteTableModel();
        tblReporte.setModel(tableModel);


        cmbFiltro.removeAllItems();
        cmbFiltro.addItem("Hoy");
        cmbFiltro.addItem("Ayer");
        cmbFiltro.addItem("Esta semana");
        cmbFiltro.addItem("Este mes");

        cargarReportePorFecha();
}
    
    private void cargarReportePorFecha() {
        LocalDate fecha = LocalDate.now();

        String filtro = (String) cmbFiltro.getSelectedItem();

        switch (filtro) {
            case "Hoy" -> fecha = LocalDate.now();
            case "Ayer" -> fecha = LocalDate.now().minusDays(1);
            case "Esta semana" -> fecha = LocalDate.now().minusDays(7);
            case "Este mes" -> fecha = LocalDate.now().minusDays(30);
        }

        List<Venta> ventas = ventaService.listarPorFecha(fecha);
        tableModel.setVentas(ventas);

        double total = ventas.stream()
                .filter(v -> "ACTIVA".equals(v.getEstado()))
                .mapToDouble(Venta::getTotal)
                .sum();

        lblTotal.setText(String.format("Total: $%,.0f", total));
}



private class ReporteTableModel extends AbstractTableModel {

    private final String[] columnas = {"ID", "Fecha", "Usuario", "Total", "Estado"};
        private List<Venta> ventas = new ArrayList<>();

        public void setVentas(List<Venta> ventas) {
            this.ventas = ventas;
            fireTableDataChanged();
        }

        @Override
        public int getRowCount() {
            return ventas.size();
        }

        @Override
        public int getColumnCount() {
            return columnas.length;
        }

        @Override
        public String getColumnName(int column) {
            return columnas[column];
        }

        @Override
        public Object getValueAt(int row, int col) {
            Venta v = ventas.get(row);

            return switch (col) {
                case 0 -> v.getId();
                case 1 -> v.getFecha().toString();
                case 2 -> v.getUsuarioNombre();
                case 3 -> String.format("$%,.0f", v.getTotal());
                case 4 -> v.getEstado();
                default -> "";
            };
        }
}    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.  
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFiltro = new javax.swing.JLabel();
        cmbFiltro = new javax.swing.JComboBox<>();
        btnGenerar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        Scroll = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblFiltro.setText("Filtro:");
        jPanel1.add(lblFiltro);

        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbFiltro);

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerar);

        lblTotal.setText("Total: $0");
        jPanel1.add(lblTotal);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Scroll.setViewportView(tblReporte);

        add(Scroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        cargarReportePorFecha();
    }//GEN-LAST:event_btnGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
