package cl.josueaguila.pnb.gui;

import cl.josueaguila.pnb.model.Usuario;
import cl.josueaguila.pnb.service.UsuarioService;
import cl.josueaguila.pnb.service.impl.UsuarioServiceStub;
import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import cl.josueaguila.pnb.controller.*;
import cl.josueaguila.pnb.app.*;


public class UsuariosPanel extends javax.swing.JPanel {
    private UsuarioTableModel tableModel;
    private Usuario usuarioSeleccionado;
    private UsuarioService usuarioService;
    private UsuarioController controller;



    public UsuariosPanel() {
        
        this.controller = ApplicationContext.getInstance().getUsuarioController();
        
        initComponents();
        setupTable();
        setupListeners();
        cargarUsuarios();
        limpiarFormulario();
    }
    
    private void cargarUsuarios() {
        try {
            List<Usuario> usuarios = controller.listarTodos();
            tableModel.setUsuarios(usuarios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar usuarios: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
}

   
    private void setupTable() {
        tableModel = new UsuarioTableModel();
        tblUsuarios.setModel(tableModel);
        tblUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        // Configurar anchos de columnas
        tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(50);  // ID
        tblUsuarios.getColumnModel().getColumn(1).setPreferredWidth(100); // Username
        tblUsuarios.getColumnModel().getColumn(2).setPreferredWidth(200); // Nombre
        tblUsuarios.getColumnModel().getColumn(3).setPreferredWidth(80);  // Rol
        tblUsuarios.getColumnModel().getColumn(4).setPreferredWidth(60);  // Activo
    }
    
    private void setupListeners() {
        // Selección en tabla
        tblUsuarios.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tblUsuarios.getSelectedRow();
                if (selectedRow >= 0) {
                    usuarioSeleccionado = tableModel.getUsuarioAt(selectedRow);
                    cargarEnFormulario(usuarioSeleccionado);
                }
            }
        });
        
        // Doble clic para editar
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int row = tblUsuarios.getSelectedRow();
                    if (row >= 0) {
                        usuarioSeleccionado = tableModel.getUsuarioAt(row);
                        cargarEnFormulario(usuarioSeleccionado);
                        txtUsername.requestFocus();
                    }
                }
            }
        });
        
        // Búsqueda en tiempo real
        txtBuscar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filtrar(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filtrar(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { }
            private void filtrar() {
                String texto = txtBuscar.getText();
                List<Usuario> usuarios = controller.buscar(texto);
                tableModel.setUsuarios(usuarios);
            }
        });
    }
    
    private void cargarEnFormulario(Usuario usuario) {
        txtUsername.setText(usuario.getUsername());
        txtPassword.setText(usuario.getPassword());
        txtNombreCompleto.setText(usuario.getNombreCompleto());
        cmbRol.setSelectedItem(usuario.getRol());
        chkActivo.setSelected(usuario.isActivo());
        
        btnEliminar.setEnabled(true);
    }
    
    private void limpiarFormulario() {
        usuarioSeleccionado = null;
        txtUsername.setText("");
        txtPassword.setText("");
        txtNombreCompleto.setText("");
        cmbRol.setSelectedIndex(0);
        chkActivo.setSelected(true);
        btnEliminar.setEnabled(false);
        txtUsername.requestFocus();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnNuevoUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        chkActivo = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lblBuscar.setText("Buscar:");
        jPanel1.add(lblBuscar);

        txtBuscar.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel1.add(txtBuscar);

        btnNuevoUsuario.setText("Nuevo Usuario");
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoUsuario);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Username:");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        txtUsername.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel2.add(txtUsername, new java.awt.GridBagConstraints());

        jLabel2.setText("Password:");
        jPanel2.add(jLabel2, new java.awt.GridBagConstraints());

        txtPassword.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel2.add(txtPassword, new java.awt.GridBagConstraints());

        jLabel3.setText("Nombre Completo:");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        txtNombreCompleto.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel2.add(txtNombreCompleto, new java.awt.GridBagConstraints());

        jLabel4.setText("Rol:");
        jPanel2.add(jLabel4, new java.awt.GridBagConstraints());

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "OPERADOR" }));
        jPanel2.add(cmbRol, new java.awt.GridBagConstraints());

        chkActivo.setText("Usuario Activo");
        jPanel2.add(chkActivo, new java.awt.GridBagConstraints());

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new java.awt.GridBagConstraints());

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new java.awt.GridBagConstraints());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new java.awt.GridBagConstraints());

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        String nombreCompleto = txtNombreCompleto.getText().trim();
        String rol = (String) cmbRol.getSelectedItem();
        boolean activo = chkActivo.isSelected();
        try {
            if (usuarioSeleccionado == null) {
                controller.crear(username, password, nombreCompleto, rol);
                JOptionPane.showMessageDialog(this,
                    "Usuario creado exitosamente",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                controller.actualizar(usuarioSeleccionado.getId(), username, password,
                                    nombreCompleto, rol, activo);
                JOptionPane.showMessageDialog(this,
                    "Usuario actualizado exitosamente",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
            }
            limpiarFormulario();
            cargarUsuarios();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Validación",
                JOptionPane.WARNING_MESSAGE);
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (usuarioSeleccionado == null) {
            return;
        }
        
        int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de eliminar el usuario '" + usuarioSeleccionado.getUsername() + "'?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);
        
        if (respuesta == JOptionPane.YES_OPTION) {
            // TODO: Eliminar en servicio
            System.out.println("[STUB] Eliminando usuario: " + usuarioSeleccionado);
            JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente");
            limpiarFormulario();
            cargarUsuarios();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (usuarioSeleccionado == null) return;
        int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Eliminar el usuario '" + usuarioSeleccionado.getUsername() + "'?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                controller.eliminar(usuarioSeleccionado.getId());
                JOptionPane.showMessageDialog(this,
                    "Usuario eliminado",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
                cargarUsuarios();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private boolean validarFormulario() {
        if (txtUsername.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El username es obligatorio", 
                "Validación", JOptionPane.WARNING_MESSAGE);
            txtUsername.requestFocus();
            return false;
        }
        
        if (txtPassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "La contraseña es obligatoria", 
                "Validación", JOptionPane.WARNING_MESSAGE);
            txtPassword.requestFocus();
            return false;
        }
        
        if (txtNombreCompleto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre completo es obligatorio", 
                "Validación", JOptionPane.WARNING_MESSAGE);
            txtNombreCompleto.requestFocus();
            return false;
        }
        
        return true;
    }
    
    private class UsuarioTableModel extends AbstractTableModel {
        private List<Usuario> usuarios = new ArrayList<>();
        private String[] columnNames = {"ID", "Username", "Nombre Completo", "Rol", "Activo"};
        
        public void setUsuarios(List<Usuario> usuarios) {
            this.usuarios = usuarios;
            fireTableDataChanged();
        }
        
        public Usuario getUsuarioAt(int row) {
            return usuarios.get(row);
        }
        
        @Override
        public int getRowCount() {
            return usuarios.size();
        }
        
        @Override
        public int getColumnCount() {
            return columnNames.length;
        }
        
        @Override
        public String getColumnName(int column) {
            return columnNames[column];
        }
        
        @Override
        public Object getValueAt(int row, int column) {
            Usuario u = usuarios.get(row);
            switch (column) {
                case 0: return u.getId();
                case 1: return u.getUsername();
                case 2: return u.getNombreCompleto();
                case 3: return u.getRol();
                case 4: return u.isActivo() ? "Sí" : "No";
                default: return null;
            }
        }
        
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
