package cl.josueaguila.pnb.gui;

import cl.josueaguila.pnb.model.Producto;
import cl.josueaguila.pnb.model.Venta;
import cl.josueaguila.pnb.service.ProductoService;
import cl.josueaguila.pnb.service.VentaService;
import cl.josueaguila.pnb.service.impl.ProductoServiceStub;
import cl.josueaguila.pnb.service.impl.VentaServiceStub;
import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.awt.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;



public class VentasPanel extends javax.swing.JPanel {
    
    private ProductoService productoService;
    private VentaService ventaService;
    private List<Producto> productosActivos;
    private VentaController controller;




    public VentasPanel() {
        
        this.controller = ApplicationContext.getInstance().getVentaController();
        this.productoService = new ProductoServiceStub();
        this.ventaService = new VentaServiceStub();
        
        initComponents();
        setupComponents();
        cargarProductos();
        cargarVentasDelDia();
        cargarVentas();
    }

    private void setupComponents() {
        // Lista de productos
        listModel = new DefaultListModel<>();
        lstProductos.setModel(listModel);
        lstProductos.setCellRenderer(new ProductoListCellRenderer());
        
        // Spinner de cantidad
        spnCantidad.setModel(new SpinnerNumberModel(1, 1, 99, 1));
        
        // Tabla de detalle
        itemsVenta = new ArrayList<>();
        detalleTableModel = new DetalleVentaTableModel();
        tblDetalle.setModel(detalleTableModel);
        
        // Tabla de ventas del día
        ventasTableModel = new VentaTableModel();
        tblVentasDelDia.setModel(ventasTableModel);
        
        actualizarTotal();
    }
    
    private void cargarVentas() {
        List<Venta> ventas = controller.listarTodos();
        tableModel.setVentas(ventas);
    }

    

    private void cargarProductos() {
        productosActivos = productoService.listarActivos();
        listModel.clear();

        for (Producto p : productosActivos) {
            listModel.addElement(p);
        }       
    }

    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProductos = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        scrollDetalle = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnQuitar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        btnConfirmarVenta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVentasDelDia = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        lblTotalDia = new javax.swing.JLabel();
        txtTotalDia = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Registro de Nueva Venta");
        jPanel5.add(jLabel2);

        add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Buscar:");
        jPanel2.add(jLabel1);

        txtBuscar.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel2.add(txtBuscar);

        btnBuscar.setText("🔍");
        jPanel2.add(btnBuscar);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(lstProductos);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel3.setText("Cantidad:");
        jPanel3.add(jLabel3);
        jPanel3.add(spnCantidad);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Detalle de la Venta");
        jPanel6.add(jLabel4);

        jPanel4.add(jPanel6, java.awt.BorderLayout.NORTH);

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollDetalle.setViewportView(tblDetalle);

        jPanel4.add(scrollDetalle, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(3, 1));

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnQuitar.setText("Quitar Seleccionado");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });
        jPanel8.add(btnQuitar);

        jPanel7.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblTotal.setText("TOTAL:");
        jPanel9.add(lblTotal);

        txtTotal.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel9.add(txtTotal);

        jPanel7.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnConfirmarVenta.setText("Confirmar Venta");
        btnConfirmarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVentaActionPerformed(evt);
            }
        });
        jPanel10.add(btnConfirmarVenta);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel10.add(btnCancelar);

        jPanel7.add(jPanel10);

        jPanel4.add(jPanel7, java.awt.BorderLayout.SOUTH);

        add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel11.setLayout(new java.awt.BorderLayout());

        tblVentasDelDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblVentasDelDia);

        jPanel11.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        lblTotalDia.setText("Total del día:");
        jPanel12.add(lblTotalDia);

        txtTotalDia.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel12.add(txtTotalDia);

        jPanel11.add(jPanel12, java.awt.BorderLayout.SOUTH);

        jLabel7.setText("Ventas del Día ");
        jPanel13.add(jLabel7);

        jPanel11.add(jPanel13, java.awt.BorderLayout.NORTH);

        add(jPanel11, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            int productoId = Integer.parseInt(txtProductoId.getText());
            int cantidad = Integer.parseInt(txtCantidad.getText());
            String usuario = txtUsuario.getText();

            controller.crearVenta(productoId, cantidad, usuario);

            JOptionPane.showMessageDialog(this, "Venta registrada correctamente");
            cargarVentas();
            limpiarFormulario();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDetalle.getSelectedRow();
        if (selectedRow >= 0) {
            itemsVenta.remove(selectedRow);
            detalleTableModel.fireTableDataChanged();
            actualizarTotal();
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnConfirmarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVentaActionPerformed
        // TODO add your handling code here:
        if (itemsVenta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Agrega al menos un producto", 
                "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double total = calcularTotal();
        
        int respuesta = JOptionPane.showConfirmDialog(this,
            String.format("¿Confirmar venta por $%,.0f?", total),
            "Confirmar Venta",
            JOptionPane.YES_NO_OPTION);
        
        if (respuesta == JOptionPane.YES_OPTION) {
            // TODO: Guardar en servicio
            Venta nueva = new Venta(
                0,
                LocalDateTime.now(),
                1,               
                "admin",        
                total,
                "ACTIVA"
            );

            ventaService.registrar(nueva);

            JOptionPane.showMessageDialog(this, "Venta registrada exitosamente");
            limpiarVenta();
            cargarVentasDelDia();
        }
    }//GEN-LAST:event_btnConfirmarVentaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (ventaSeleccionada == null) return;

        int resp = JOptionPane.showConfirmDialog(this,
            "¿Cancelar esta venta?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);

        if (resp == JOptionPane.YES_OPTION) {
            try {
                controller.cancelarVenta(ventaSeleccionada.getId());
                cargarVentas();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed


    private void actualizarTotal() {
        double total = itemsVenta.stream()
                .mapToDouble(ItemVenta::getSubtotal)
                .sum();

        txtTotal.setText(String.format("$%,.0f", total));
}   
    
    
    private void limpiarVenta() {
        itemsVenta.clear();
        detalleTableModel.fireTableDataChanged();
        actualizarTotal();
        lstProductos.clearSelection();
        spnCantidad.setValue(1);
    }

    private double calcularTotal() {
        return itemsVenta.stream()
            .mapToDouble(ItemVenta::getSubtotal)
            .sum();
    }
    
    
    private void cargarVentasDelDia() {
        
        List<Venta> ventas = ventaService.listarVentasDelDia();
        ventasTableModel.setVentas(ventas);

        double totalDia = ventas.stream()
            .filter(v -> "ACTIVA".equals(v.getEstado()))
            .mapToDouble(Venta::getTotal)
            .sum();

        txtTotalDia.setText(String.format("$%,.0f", totalDia));
    }
        
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalDia;
    private javax.swing.JList<Producto> lstProductos;
    private javax.swing.JScrollPane scrollDetalle;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTable tblVentasDelDia;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalDia;
    // End of variables declaration//GEN-END:variables
   
private List<ItemVenta> itemsVenta;
private DefaultListModel<Producto> listModel;
    
private DetalleVentaTableModel detalleTableModel;
private VentaTableModel ventasTableModel;
    
    private class ItemVenta {
        private Producto producto;
        private int cantidad;
        
        public ItemVenta(Producto producto, int cantidad) {
            this.producto = producto;
            this.cantidad = cantidad;
        }
        
        public Producto getProducto() { return producto; }
        public int getCantidad() { return cantidad; }
        public void setCantidad(int cantidad) { this.cantidad = cantidad; }
        public double getSubtotal() { return producto.getPrecio() * cantidad; }
    }
    
    private class DetalleVentaTableModel extends AbstractTableModel {
        private String[] columnNames = {"Producto", "Cantidad", "Precio Unit.", "Subtotal"};
        
        @Override
        public int getRowCount() { return itemsVenta.size(); }
        
        @Override
        public int getColumnCount() { return columnNames.length; }
        
        @Override
        public String getColumnName(int column) { return columnNames[column]; }
        
        @Override
        public Object getValueAt(int row, int column) {
            ItemVenta item = itemsVenta.get(row);
            switch (column) {
                case 0: return item.getProducto().getNombre();
                case 1: return item.getCantidad();
                case 2: return String.format("$%,.0f", item.getProducto().getPrecio());
                case 3: return String.format("$%,.0f", item.getSubtotal());
                default: return null;
            }
        }
        
        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    }
    
    private class VentaTableModel extends AbstractTableModel {
        private List<Venta> ventas = new ArrayList<>();
        private String[] columnNames = {"#", "Fecha/Hora", "Usuario", "Total", "Estado"};
        
        public void setVentas(List<Venta> ventas) {
            this.ventas = ventas;
            fireTableDataChanged();
        }
        
        @Override
        public int getRowCount() { return ventas.size(); }
        
        @Override
        public int getColumnCount() { return columnNames.length; }
        
        @Override
        public String getColumnName(int column) { return columnNames[column]; }
        
        @Override
        public Object getValueAt(int row, int column) {
            Venta v = ventas.get(row);
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yy HH:mm");
            switch (column) {
                case 0: return v.getId();
                case 1: return v.getFechaHora().format(formatter);
                case 2: return v.getUsuarioNombre();
                case 3: return String.format("$%,.0f", v.getTotal());
                case 4: return v.getEstado();
                default: return null;
            }
        }
        
        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    }
    
    // Renderer personalizado para la lista de productos
    private class ProductoListCellRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, 
                int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            
            if (value instanceof Producto) {
                Producto p = (Producto) value;
                setText(String.format("<html><b>%s</b><br><small>$%,.0f</small></html>", 
                    p.getNombre(), p.getPrecio()));
            }
            
            return this;
        }
    }
    
}

